#!/bin/bash
set -eu

source /usr/share/yunohost/helpers

ynh_script_progression --message="Updating write_nostr URL..." --weight=1
ynh_config_change_url_nginx

ynh_script_progression --message="write_nostr URL update complete" --last
