#!/bin/bash
set -eu

source /usr/share/yunohost/helpers

ynh_script_progression --message="Removing write_nostr Nginx configuration..." --weight=1
ynh_config_remove_nginx

ynh_script_progression --message="Removing write_nostr files..." --weight=1
ynh_safe_rm "$install_dir"

ynh_script_progression --message="write_nostr removal complete" --last
